{% set name = "pygridmet" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygridmet-{{ version }}.tar.gz
  sha256: 5ad34bc0b8116295411d58f0adb075ca2d43f48b1a80371b5eb65cb961245b60

build:
  entry_points:
    - pygridmet = pygridmet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - async-retriever <0.19,>=0.18
    - click >=0.7
    - geopandas-base >=1
    - numpy >=1.21
    - pandas >=1
    - pygeoogc <0.19,>=0.18
    - pygeoutils <0.19,>=0.18
    - pyproj >=3.0.1
    - shapely >=2
    - xarray >=2023.01

test:
  imports:
    - pygridmet
  commands:
    - pip check
    - pygridmet --help
  requires:
    - pip

about:
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  home: https://github.com/hyriver/pygridmet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
