{% set name = "pygridmet" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygridmet-{{ version }}.tar.gz
  sha256: 85c6ed53cb8b64dbb1b85128b416b1e93702aa87826064e15fc6ca6ac93557d2

build:
  entry_points:
    - pygridmet = pygridmet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - click >=0.7
    - netcdf4
    - numpy >=2
    - pandas >=1
    - pyproj >=3.0.1
    - rioxarray >=0.15
    - shapely >=2
    - tiny-retriever >=0.1.3
    - xarray >=2024.7

test:
  imports:
    - pygridmet
  commands:
    - pip check
    - pygridmet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  home: https://github.com/hyriver/pygridmet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
