{% set name = "pygridmet" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygridmet-{{ version }}.tar.gz
  sha256: a4d958304e9ec4629219a9e78c31068f1a4c05ec6a6893bf004569dcdff9e2bf

build:
  entry_points:
    - pygridmet = pygridmet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles
    - aiohttp >=3.8.3
    - click >=0.7
    - netcdf4
    - numpy >=2
    - pandas >=1
    - pyproj >=3.0.1
    - rioxarray >=0.15
    - shapely >=2
    - xarray >=2024.7

test:
  imports:
    - pygridmet
  commands:
    - pip check
    - pygridmet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  home: https://github.com/hyriver/pygridmet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
